### ISSUE TITLE
[BUG] [BETA] Editor buttons should not be clickthrough elements.

### ISSUE THREAD

**Issue by sgtoutlaw** [EliteMasterEric/Teyvat.moe#156]
This is a two part issue but they were related to the same thing so I wasn't sure how to format it.

**Describe the bug**
1.
The editor buttons being clickthrough creates a couple of problems.   If I click the marker button, and before making a mark, decide to click the marker or routing button again, I will leave a marker behind those buttons.

2.
If you start to make a route, and have not completed it, and try to press one of the editor buttons to finalize the end of the route, the route follows up and ends it at the editor button instead.  Even worse is there is also something wrong with how the app ends the route when changing over to the marker tool, so that route won't show up in your editor list and the only way to get rid of it is to refresh the page.

**To Reproduce**
  1. Go into editor mode
  2. Click on the marker button.
  3. Click on the marker button again or the routing button.
  4. See as a marker is placed behind them.

**

  1. Go into editor mode
  2. Click on the routing button.
  3. Start making a route.
  4. Click onto the marker button.
  5. The route will go to the marker button, and the route will not appear in elements list.
Note:  For this to happen, your editor buttons have to be over a markable section of the map of course.

**Expected behavior**
The buttons should not allow the tools to work through them, and the routing should cleanly finish at the last made point and pop up in the elements list. 

**Screenshots**

1.
https://user-images.githubusercontent.com/35310360/102963239-976a6100-44b6-11eb-9b7c-f5b0e76603b2.mp4

2.
https://user-images.githubusercontent.com/35310360/102963759-f2508800-44b7-11eb-8ebf-4b98c91aafea.mp4

Sorry about this being like 2 bugs, but due to the fact that they involve the same problem I wasn't sure if it wasn't better to know of them at the same time cause they might have the same fixes.

**Comment by EliteMasterEric** [comment]
So, I think I may have info on the general causes of these two bugs. They are somewhat tricky and will take a while to solve, sadly.

1. After updating some of the libraries the map uses, one feature that was sadly removed was the ability to properly add a custom control. I found a workaround to do this but it appears to have this side effect. I'm tinkering around and I think it has to do with the CSS?

2. The issue here is with how the editor functions. In order to have the route render from the user data, I have to do some special processing as the map is finalized. Currently I do this when clicking the last vertex, but it appears there is an edge case where that event does not get called.

Thank you so much for reporting these, and overall for the work you've put into contributing markers.

**Comment by EliteMasterEric** [comment]
@sgtoutlaw These were more complex fixes than I anticipated, but it's done.

In v0.9.3 (the uploaded Beta version), the editor controls have been reworked. Aside from a minor stylistic upgrade with improved icons and hover tooltips, the buttons are no longer clickthrough. Additionally, when marker placement is active, the buttons will be hidden and a Cancel button (which stops the current edit operation) will display. When route placement is active, the Cancel button will display alongside a Done button, which functions the same as clicking the last vertex of the route.

I hope these changes make your experience better. I am grateful for the work you have done mapping so far, and I highly appreciate any feedback users provide, whether it regards suggestions for new features or complications which make the app more difficult to use. Please feel free to create a new issue if you have any further concerns.
