### ISSUE TITLE
[FEATURE] Create script to import new data from Yuanshen.site

### ISSUE THREAD

**Issue by ichups11** [EliteMasterEric/Teyvat.moe#180]
**Is your feature request related to a problem? Please describe.**
There is still no chests in the map and if I'm not wrong, this map is based on the Yuanshen.site interactive map.

**Describe the solution you'd like**
The current yuanshen.site already has updated chests on Dragonspine but loads so slow, it would be wonderful if you were able to import the chests in there to this map.

**Describe alternatives you've considered**
...

**Additional context**
Thank you so much for this amazing project!

**Comment by EliteMasterEric** [comment]
This site WAS based on Yuanshen.site. It is now independently maintained. Notably, the way markers are stored is similar (the same coordinates are used).

I now see that there ARE new chests on Yuanshen, including many in Dragonspine, which is very nice since we can import many of those, and most of them have screenshots. The one issue with this is that the chests are unsorted (no rarity specified), but the provided screenshots can help with this.

Thank you for pointing out that Yuanshen has updated! I will look into this soon.
