### ISSUE TITLE
[BUG] North Qingyun Peak Teleporter misplaced

### ISSUE THREAD

**Issue by grantwwu** [EliteMasterEric/Teyvat.moe#191]
**Describe the bug**

North Qingyun Peak Teleporter is not where it should be.

**To Reproduce**

1. Go to https://genshinmap.github.io/
2. Scroll to the location of the North Qingyun Peak Teleporter.
3. Zoom in

**Screenshots**

What it looks like in game
https://i.imgur.com/jAlbslM.png

What it looks like in the map
https://i.imgur.com/tXMScdh.png

**Device Specs (please complete the following information):**

- GenshinMap app version: 0.9.4
- Device: PC
- OS: Windows 10
- Browser: Chrome
- Browser Version: 87.0.4280.88

**Error Message**

**Additional context**

**Comment by EliteMasterEric** [comment]
I encountered this when I used the teleporter myself and forgot to fix it.

The difference is significant, because one puts you on top of the ledge and the other means you must climb.

The reason for this problem was that, prior to the map fixes that happened in v0.9.0, the maximum zoom level wasn't very close (since every zoom level had to have its own set of images, meaning that to zoom in more would have required creating thousands of blurry images). With the fix, the map is now stretched beyond a certain zoom level, meaning you can place markers much more precisely now.

Thank you for reporting, I'll leave this issue up as a reminder to fix the problem.

**Comment by EliteMasterEric** [comment]
Fixed in v0.9.5.
