### ISSUE TITLE
[BUG] Module not found at cloned master branch

### ISSUE THREAD

**Issue by luanvilarim** [EliteMasterEric/Teyvat.moe#235]
**Describe the bug**

Hello! I just cloned the project and as I tried to run it locally I got the error below.

I saw that you use custom paths on the project and the configuration within it seems to be fine.
I was also messing around with the path displayed on the error and it seems to change the error message to another path when I change `~/components` to `./components`. So I was wondering if you had any configurations on your environment (outside of the project perhaps), that I might be missing in order to get the correct paths when I run it.

**To Reproduce**

1. Clone the project into a folder
2. Run the `npm install` command
3. Run `npm run start:dev` command

**Error Message**

```
./src/App.js
Module not found: Can't resolve './src/components/Theme'
```

**Additional context**
I am using the latest Node build  (v14.15.3) and VS Code as IDE.
Tried the master and the dev branches with no success. I think there's more steps to it than the ones I mentioned above.

Thanks for the help!

**Comment by EliteMasterEric** [comment]
Hey,

I do not understand why this error is occurring for you.

I am using the `babel-plugin-root-import` to make paths absolute rather than relative, which prevents having imports like `../../../../../../Theme`. However, the plugin configuration does appear to be included in the project.

I am using Node `12.19.0` and VS Code `1.52.1`. I cloned the project to my other laptop and it ran fine there on node `10.19.0`. On that laptop, I just downloaded node `14.15.3`, cloned the project fresh, and ran `npm install` and `npm run start:dev` and it worked fine.

Where are you seeing the error? Is it being output by node or VSCode?

**Comment by luanvilarim** [comment]
I figured it out. My root directory had some special characters (Portuguese is my native language) so it must've messed with the babel plugin. Thanks for the help!

**Comment by EliteMasterEric** [comment]
@luanvilarim Good to hear you've resolved your issue.

If you can reliably reproduce the problem, I recommend posting it to the GitHub repository for the plugin: https://github.com/entwicklerstube/babel-plugin-root-import

Hopefully they can fix the issue so others do not experience it.
