### ISSUE TITLE
[FEATURE] Option to use double click or switch.

### ISSUE THREAD

**Issue by sgtoutlaw** [EliteMasterEric/Teyvat.moe#250]
Please give me an option to use the double clicking for hiding the markers, possible among the marker options.  

That was a huge boon for me, as all the others already have the switches and are more of a pain to work with personally.  This allowed me to feel like I was spending less time messing with the map and actually playing the game.

I know you probably put a lot of work into it.  I love the new interface after all.

**Comment by EliteMasterEric** [comment]
Thanks for the compliment, I've been working really hard over the past week to make these improvements to fix things up.

This is for the Beta v0.10.0 site? I completely redid how markers are stored and rendered, with one of the benefits of this being that I could finally add interactive elements to the popups. I standardized the marker IDs so that I don't have to redo them for every submission. I also added fields that specify who contributed the marker, as well as which IDs this marker is identified by on other sites. 

This last feature requires a lot of manual data entry (I've only done it for Crimson Agates so far) but it's necessary infrastructure for a feature I've wanted to implement since the project started; AppSample and MapGenie importers.

I probably should have labelled this somewhere but I consider this an alpha version, a bunch of stuff is inconsistent right now. Among other things, note that progress on the big three (Anemoculus, Geoculus, and Agates) is currently "wiped" (it's still there but not being accessed), and additionally any markers which don't use the new data format still use the old marker rendering (and thus you can double click to mark them and the popup has no switch),

The double click behavior being missing is definitely an oversight though, the intent was for both functions to always be enabled. I'll be developing that next (and adding a debounce to it to fix issue #220).

**Comment by EliteMasterEric** [comment]
Double-click readded in the v0.10.1 alpha version.
