### ISSUE TITLE
[BUG] Clear Expired

### ISSUE THREAD

**Issue by hey2022** [EliteMasterEric/Teyvat.moe#304]
**Clear Expired does nothing**

**To Reproduce**

1. Mark a renewable resource
2. Wait until refresh time or change system time
3. Go to summary tab and try to clear the object
4. Does nothing

**Screenshots**

**Device Specs (please complete the following information):**

- GenshinMap app version: [see options tab, e.g. 'App version: v0.10.8 but the problem was happening before-]
- Device: [Lenovo Think Center]
- OS: [Ubuntu 20.04]
- Browser: [Firefox]
- Browser Version: [85.0 (64-bit)]

**Error Message**

```

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://c0ee3e46-9759-49f6-8951-3be43673f4f6/content/js/purify.min.js
Source Map URL: purify.min.js.map

Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). fingerprint-protection.js:343:25
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). inject.js:22:29
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). inject.js:41:35
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). utils.js:35:9
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 fingerprint-protection.js:343:25
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead. leaflet-src.js:28:5

```

**Additional context**
No error pops up when clicking clear expired

**Comment by EliteMasterEric** [comment]
The warnings that appear in your console (aside from the last line) appear to be related to an extension you have installed in your browser. Note the `moz-extension://` at the beginning.

The last line (mozPressure) is caused by Leaflet/Leaflet#3943 and sadly isn't actionable.

The Clear Expired feature not working seems to be an issue though. I'll look into it.

**Comment by hey2022** [comment]
Just saying Import/Export doesn't track the time of marking
so clear expired times will reset when importing data

**Comment by hey2022** [comment]
Refreshing the site also resets the mark time to the time of refresh

**Comment by EliteMasterEric** [comment]
@hey2022 I've deduced the cause of the bug. Import/Export is properly outputting the time of marking and refreshing the site does not reset the time of marking. The bug is that opening the popup (to view the completion time of a marker) causes the completion time of that marker to reset.

I have replicated and resolved the issue and the fix should come in a patch some time soon.
