### ISSUE TITLE
[FIX] Update deprecated map pattern

### ISSUE THREAD

**Issue by TheEZIC** [EliteMasterEric/Teyvat.moe#305]
Ingame:
![image](https://user-images.githubusercontent.com/35061249/107027460-36c08a80-67bd-11eb-8349-fd90c83364ce.png)
On map:
![image](https://user-images.githubusercontent.com/35061249/107027492-42ac4c80-67bd-11eb-994a-65608db58c8b.png)

**Comment by hey2022** [comment]
also there's a teleporter in the pond
![image](https://user-images.githubusercontent.com/48553457/107028828-326a9080-6802-11eb-9cb4-50a93fe64cb1.png)

**Comment by EliteMasterEric** [comment]
Hey, thanks for pointing both of these out.

These two issues were likely due to the map not supporting higher zoom levels until... v0.9 or so? The teleporters were placed much earlier and thus weren't placed too precisely.

EDIT: See #191 where a similar fix was made to a different marker.

I think now is a good time for me to go through and do a cleanup pass on all the statues, teleporters, and domains.

**Comment by EliteMasterEric** [comment]
Will be fixed in v0.12.5.
