### ISSUE TITLE
All the chests are gone. And all my marks too.

### ISSUE THREAD

**Issue by DS2902** [EliteMasterEric/Teyvat.moe#32]
After updating the map. All the chests are gone. And all my marks too.

**Comment by Izuzusama** [comment]
I made a temporary backup website at https://izuzu.bitbucket.io/

To get all your old stuff back to the backup website

1. Goto https://genshinmap.github.io/
2. Press F12 on your keyboard
3. Select Console tab
4. Paste this into the console `prompt("Copy the below text: ", JSON.stringify(window.localStorage))`
5. Copy the content in the popup, you can now dismiss the popup
6. Goto https://izuzu.bitbucket.io/
7. Click on 'Import from genshinmap.github.io'
8. Paste the copied text and press OK

**Comment by DS2902** [comment]
No. After import, my collected marks did not appear.

**Comment by DS2902** [comment]
As it appears. The import data from the new version does not match the old one. Although in the new one I did not make any marks or reset.
This is complete fucked up.

**Comment by Exsuplosion** [comment]
same here. i tried that aswell but my chest are still not shown as looted

**Comment by NOMHS** [comment]
After the update all my marks are gone too but I have been using the map in my mobile browser (Chrome) so I can't even try out the solution up there. What can I do to get all my stuff back?

**Comment by schrmh** [comment]
@NOMHS Try this https://stackoverflow.com/a/37256485/7031100

**Comment by NOMHS** [comment]
@schrmh Thank you so much! I could import it that way but unfortunately the marks didn't reappear.

**Comment by birth23** [comment]
It is not working because the prompt is cutting off the string by truncating and adding "..." in the middle.  The string is too long. 
The steps provided by @Izuzusama are valid but instead of the above formula You need to paste the following into your console: `console.log(JSON.stringify(window.localStorage))` 

1. Go to https://genshinmap.github.io/
2. Press F12 on your keyboard
3. Select Console tab
4. Paste this into the console `console.log(JSON.stringify(window.localStorage))` 
5. Copy the all string of text from your console
6. Goto https://izuzu.bitbucket.io/
7. Click on 'Import from genshinmap.github.io'
8. Paste the copied text and press OK

**Comment by birth23** [comment]
> I made a temporary backup website at https://izuzu.bitbucket.io/
> 
> To get all your old stuff back to the backup website
> 
> 1. Goto https://genshinmap.github.io/
> 2. Press F12 on your keyboard
> 3. Select Console tab
> 4. Paste this into the console `prompt("Copy the below text: ", JSON.stringify(window.localStorage))`
> 5. Copy the content in the popup, you can now dismiss the popup
> 6. Goto https://izuzu.bitbucket.io/
> 7. Click on 'Import from genshinmap.github.io'
> 8. Paste the copied text and press OK

It is not working because the prompt is cutting off the string by truncating and adding "..." in the middle. The string is too long.
The steps provided by @Izuzusama are valid but instead of the above command You need to paste the following into your console: `console.log(JSON.stringify(window.localStorage))`

1. Go to https://genshinmap.github.io/
2. Press F12 on your keyboard
3. Select Console tab
4. Paste this into the console `console.log(JSON.stringify(window.localStorage))`
5. Copy the all string of text from your console
6. Goto https://izuzu.bitbucket.io/
7. Click on 'Import from genshinmap.github.io'
8. Paste the copied text and press OK

**Comment by Exsuplosion** [comment]
WORKS, VERRY NIICE TY

**Comment by Izuzusama** [comment]
right dint think about the string too long

**Comment by fcpn90** [comment]
> > I made a temporary backup website at https://izuzu.bitbucket.io/
> > To get all your old stuff back to the backup website
> > 
> > 1. Goto https://genshinmap.github.io/
> > 2. Press F12 on your keyboard
> > 3. Select Console tab
> > 4. Paste this into the console `prompt("Copy the below text: ", JSON.stringify(window.localStorage))`
> > 5. Copy the content in the popup, you can now dismiss the popup
> > 6. Goto https://izuzu.bitbucket.io/
> > 7. Click on 'Import from genshinmap.github.io'
> > 8. Paste the copied text and press OK
> 
> It is not working because the prompt is cutting off the string by truncating and adding "..." in the middle. The string is too long.
> The steps provided by @Izuzusama are valid but instead of the above command You need to paste the following into your console: `console.log(JSON.stringify(window.localStorage))`
> 
> 1. Go to https://genshinmap.github.io/
> 2. Press F12 on your keyboard
> 3. Select Console tab
> 4. Paste this into the console `console.log(JSON.stringify(window.localStorage))`
> 5. Copy the all string of text from your console
> 6. Goto https://izuzu.bitbucket.io/
> 7. Click on 'Import from genshinmap.github.io'
> 8. Paste the copied text and press OK

Is there a way to do this in a iOS device Chrome app? All my marks are gone.

**Comment by Izuzusama** [comment]
Via console no, need to wait for #34

**Comment by EliteMasterEric** [comment]
See #34, I will be reverting the map to its previous version until the rework is complete.

**Comment by DS2902** [comment]
> See #34, I will be reverting the map to its previous version until the rework is complete.

After rolling back the map version, my marks returned. 👍

Better do the new version at a different address. So that we can test it too.
Thank you very much.
