### ISSUE TITLE
English Translate plz

### ISSUE THREAD

**Issue by DemonRem** [EliteMasterEric/Teyvat.moe#7]
can the map be translated to english please?

**Comment by EliteMasterEric** [comment]
Translating the ingame map requires the following steps:

1. Taking screenshots of the map, at various zoom levels. If images of the map could be taken that don't include region names or domain icons/teleport points, that would be nice. 
2. Convert the map into tiles. [This user discusses their attempts to figure out this process](https://gis.stackexchange.com/questions/339034/how-to-create-regional-map-tiles-for-leaflet). It would be a massive PITA to do manually.
3. Add them to the map application. This is the easy step.

In a perfect world, we would be able to extract the game's graphical assets, take the original map file, then continue at step 2. Sadly, the game's files are encrypted somehow and nobody's cracked it yet.

If anyone wants to take a crack at this, be my guest, but this is a lower priority issue since the map is functional as long as the filter controls are translated.

**Comment by EliteMasterEric** [comment]
I've made a breakthrough and managed to successfully extract the original map graphics from the game. Using this, I have generated a new map with no clutter or landmarks.

I'm working on a new version of the map in the `react` branch but I'll backport the graphics to the old one for now.

**Comment by DemonRem** [comment]
How i can use react what is thet

**Comment by EliteMasterEric** [comment]
Fixed in #9.
